import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.addItem': 'Add Item',
    'nav.locations': 'Locations',
    'nav.categories': 'Categories',
    'nav.lists': 'Lists',
    'nav.analytics': 'Analytics',
    'nav.logout': 'Logout',
    
    // Landing Page
    'landing.title': 'Never Let Food Go to Waste Again',
    'landing.heroTitle': 'Never let food go to waste again',
    'landing.heroSubline': 'Track expiry dates, get smart reminders, and save money.',
    'landing.subtitle': 'Smart expiry tracking for your kitchen. Get notified before items expire and reduce food waste while saving money.',
    'landing.getStarted': 'Get Started',
    'landing.learnMore': 'Learn More',
    'landing.downloadApp': 'Download App',
    'landing.download': 'Download',
    'landing.trustOffline': 'Offline mode',
    'landing.trustSync': 'Cloud sync',
    'landing.trustPrivacy': 'Privacy-first',
    'landing.smartAlerts': 'Smart Alerts',
    'landing.badgeTrack': 'Track items',
    'landing.badgeReminders': 'Reminders',
    'landing.badgeSaveMoney': 'Save money',
    'landing.howItWorks': 'How it works',
    'landing.step1Title': 'Add items',
    'landing.step1Desc': 'Choose category and location for each item.',
    'landing.step2Title': 'Set expiry date',
    'landing.step2Desc': 'Enter or scan the expiry date so we can track it.',
    'landing.step3Title': 'Get reminders',
    'landing.step3Desc': 'We notify you before items expire so you can use them in time.',
    'landing.screenshotsTitle': 'See the app in action',
    'landing.screenshotList': 'Items List',
    'landing.screenshotCategories': 'Setup Categories',
    'landing.screenshotCalendar': 'Calendar View',
    'landing.screenshotAddPhoto': 'Add Photo',
    'landing.screenshotSettingsTheme': 'Theme & Settings',
    'landing.screenshotListDesc': 'Browse and filter your items, search by name, and see expiry status at a glance.',
    'landing.screenshotCategoriesDesc': 'Pick category themes to quickly add suggested categories to your list.',
    'landing.screenshotCalendarDesc': 'View items by date and see what’s expiring on any day.',
    'landing.screenshotAddPhotoDesc': 'Add a photo by taking one, choosing from gallery, or using a food emoji.',
    'landing.screenshotSettingsThemeDesc': 'Change language, pick a theme, and manage app preferences.',
    'landing.worksOfflineSync': 'Works offline • Sync across devices',
    'landing.privacyFirstTitle': 'Privacy-first by design',
    'landing.privacyNoSell': 'No selling your data',
    'landing.privacyEncrypted': 'Encrypted in transit',
    'landing.privacyControl': 'You control deletion',
    'landing.privacyPolicyLink': 'Privacy Policy',
    'landing.termsLink': 'Terms & Conditions',
    'landing.whyChoose': 'Why Choose Expiry Alert?',
    'landing.smartTracking': 'Smart Tracking',
    'landing.smartTrackingDesc': 'Easily track expiry dates for all your food items with our intuitive interface.',
    'landing.timelyAlerts': 'Timely Alerts',
    'landing.timelyAlertsDesc': 'Get notified before items expire so you can use them in time.',
    'landing.visualDashboard': 'Visual Dashboard',
    'landing.visualDashboardDesc': 'See your inventory at a glance with color-coded status indicators.',
    'landing.reduceWaste': 'Reduce Waste',
    'landing.reduceWasteDesc': 'Help the environment by reducing food waste and saving money.',
    'landing.crossPlatform': 'Cross-Platform',
    'landing.crossPlatformDesc': 'Available on web, iOS, and Android for seamless synchronization.',
    'landing.securePrivate': 'Secure & Private',
    'landing.securePrivateDesc': 'Your data is securely stored and synchronized across all devices.',
    'landing.downloadTitle': 'Download Expiry Alert',
    'landing.downloadDesc': 'Get the mobile app for the best experience with notifications and offline access.',
    'landing.preferBrowser': 'Prefer to use it in your browser?',
    'landing.launchWebApp': 'Launch Web App',
    'landing.activeUsers': 'Active Users',
    'landing.itemsTracked': 'Items Tracked',
    'landing.wasteReduced': 'Food Waste Reduced',
    'landing.appStoreRating': 'App Store Rating',
    
    // Dashboard
    'dashboard.recentItems': 'Recent Items',
    'dashboard.getStarted': 'Add your first food item to get started with tracking expiry dates!',
    'dashboard.welcome': 'Welcome! Manage your food items and track expiry dates.',
    'dashboard.fresh': 'Fresh',
    'dashboard.expiringSoon': 'Expiring Soon',
    'dashboard.expired': 'Expired',
    'dashboard.total': 'Total',
    'dashboard.items': 'Items',
    'dashboard.search': 'Search items...',
    'dashboard.noItems': 'No items found',
    'dashboard.addFirstItem': 'Add your first food item to start tracking!',
    'dashboard.confirmDelete': 'Are you sure you want to delete this item?',
    'dashboard.itemDeleted': 'Item deleted successfully',
    'dashboard.deleteFailed': 'Failed to delete item',
    'dashboard.deleteMultiple': 'Delete {count} items?',
    'dashboard.itemsDeleted': '{count} items deleted',
    'dashboard.deleteFailedMultiple': 'Failed to delete items',
    'dashboard.uncategorized': 'Uncategorized',
    'dashboard.unknown': 'Unknown',
    'dashboard.noLocation': 'No location',
    'dashboard.allCategories': 'All Categories',
    'dashboard.allLocations': 'All Locations',
    'dashboard.sortByExpiry': 'Sort by Expiry',
    'dashboard.sortByName': 'Sort by Name',
    'dashboard.sortByCategory': 'Sort by Category',
    'dashboard.sortByLocation': 'Sort by Location',
    'dashboard.sortByDateAdded': 'Sort by Date Added',
    'dashboard.ascending': 'Ascending',
    'dashboard.descending': 'Descending',
    'dashboard.gridView': 'Grid View',
    'dashboard.listView': 'List View',
    'dashboard.itemsSelected': '{count} item(s) selected',
    'dashboard.deleteSelected': 'Delete Selected',
    'dashboard.clearSelection': 'Clear Selection',
    'dashboard.statusFresh': 'Fresh',
    'dashboard.statusExpiringSoon': 'Expiring Soon',
    'dashboard.statusExpired': 'Expired',
    'dashboard.daysAgo': '{count} days ago',
    'dashboard.daysLeft': '{count} days left',
    'dashboard.freshItems': 'Fresh Items',
    'dashboard.expiringItems': 'Expiring Items',
    'dashboard.expiredItems': 'Expired Items',
    'dashboard.loadDataFailed': 'Failed to load data',
    'dashboard.loadCategoriesFailed': 'Failed to load categories',
    'dashboard.loadLocationsFailed': 'Failed to load locations',
    'dashboard.unknownError': 'Unknown error',
    'dashboard.checkConnection': 'Please check your internet connection and try again.',
    
    // Home/Welcome
    'home.welcome': 'Welcome Back!',
    'home.categories': 'Categories',
    
    // Status
    'status.indate': 'In-date',
    'status.expiring': 'Expiring Soon',
    'status.expired': 'Expired',
    'status.items': 'Items',
    'status.loading': 'Loading...',
    'status.error': 'Error',
    'status.retry': 'Retry',
    'status.refresh': 'Refresh',
    'status.viewAll': 'View All',
    'status.noItems': 'No {status} items found',
    'status.itemsStored': 'Items Stored',
    'status.total': 'Total',
    
    // Items
    'item.quantity': 'Quantity',
    'item.expirestoday': 'Expires today',
    'item.dayLeft': 'day left',
    'item.daysLeft': 'days left',
    'item.dayAgo': 'day ago',
    'item.daysAgo': 'days ago',
    
    // Actions
    'action.add': 'Add',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'actions.refresh': 'Refresh',
    'actions.retry': 'Retry',
    
    // Alerts
    'alert.deleteMessage': 'Are you sure you want to delete',
    'alert.success': 'Success',
    'alert.deleteFailed': 'Failed to delete item',
    
    // Form
    'form.itemName': 'Item',
    
    // Lists
    'list.noItems': 'No items found. Add some items to get started!',
    
    // Cleanup
    'cleanup.confirmMessage': 'Are you sure you want to cleanup expired items?',
    'cleanup.success': 'Cleanup completed successfully',
    'cleanup.failed': 'Failed to cleanup expired items',
    'cleanup.itemsDeleted': 'items deleted',
    'cleanup.cleanupExpired': 'Cleanup Expired',
    'cleanup.inProgress': 'Cleaning up...',
    
    // Categories  
    'categories.title': 'Categories',
    'categories.addNew': 'Add New Category',
    'categories.name': 'Category Name',
    'categories.description': 'Description',
    'categories.icon': 'Icon',
    'categories.color': 'Color',
    'categories.delete': 'Delete Category',
    'categories.deleteConfirm': 'Are you sure you want to delete this category?',
    'categories.edit': 'Edit Category',
    'categories.save': 'Save Category',
    'categories.cancel': 'Cancel',
    'categories.noCategories': 'No categories found. Add your first category to get started!',
    'categories.preview': 'Preview',
    
    // Locations
    'locations.title': 'Storage Locations',
    'locations.addNew': 'Add New Location',
    'locations.name': 'Location Name',
    'locations.description': 'Description',
    'locations.temperature': 'Temperature',
    'locations.room': 'Room Temperature',
    'locations.refrigerated': 'Refrigerated',
    'locations.frozen': 'Frozen',
    'locations.delete': 'Delete Location',
    'locations.deleteConfirm': 'Are you sure you want to delete this location?',
    'locations.edit': 'Edit Location',
    'locations.save': 'Save Location',
    'locations.cancel': 'Cancel',
    'locations.noLocations': 'No locations found. Add your first storage location to get started!',
    
    // Food Items
    'foodItems.title': 'Food Items',
    'foodItems.addNew': 'Add New Item',
    'foodItems.name': 'Item Name',
    'foodItems.category': 'Category',
    'foodItems.location': 'Storage Location',
    'foodItems.expiryDate': 'Expiry Date',
    'foodItems.quantity': 'Quantity',
    'foodItems.notes': 'Notes',
    'foodItems.reminderDays': 'Reminder Days',
    'foodItems.save': 'Save Item',
    'foodItems.cancel': 'Cancel',
    'foodItems.edit': 'Edit Item',
    'foodItems.delete': 'Delete Item',
    'foodItems.deleteConfirm': 'Are you sure you want to delete this item?',
    'foodItems.noItems': 'No food items found. Add your first item to start tracking!',
    'foodItems.selectCategory': 'Select category',
    'foodItems.selectLocation': 'Select location',
    'foodItems.notFound': 'Item not found',
    'foodItems.loadFailed': 'Failed to load item',
    'foodItems.createFailed': 'Failed to create item',
    'foodItems.updateFailed': 'Failed to update item',
    'foodItems.loadCategoriesFailed': 'Failed to load categories and locations',
    'foodItems.groupLoadFailed': 'Unable to load your group. Please try refreshing the page.',
    'foodItems.categoryNotFound': "Don't see your category?",
    'foodItems.locationNotFound': 'Need a new location?',
    'foodItems.reminderDaysDesc': 'Number of days before expiry to remind you (default: 3 days)',
    'foodItems.tips': 'Tips:',
    'foodItems.tip1': 'Be specific with item names for easy identification',
    'foodItems.tip2': 'Double-check expiry dates to avoid mistakes',
    'foodItems.tip3': 'Use the notes field for special storage instructions',
    'foodItems.tip4': 'Set reminder days based on how quickly you use the item',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.created': 'Created',
    
    // Validation
    'validation.required': 'This field is required',
    'validation.nameRequired': 'Name is required',
    'validation.categoryRequired': 'Category is required',
    'validation.locationRequired': 'Location is required',
    'validation.dateRequired': 'Date is required',
    'validation.quantityRequired': 'Quantity is required',
    
    // Auth
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.demo': 'Demo Mode',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.displayName': 'Display Name',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.createAccount': 'Create Account',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.dontHaveAccount': "Don't have an account?",
    
    // Emoji Categories
    'emojiCategory.food': 'Food & Beverages',
    'emojiCategory.personalCare': 'Personal Care & Beauty',
    'emojiCategory.medical': 'Medical & Health',
    'emojiCategory.household': 'Household Items',
    'emojiCategory.chemical': 'Chemical & Automotive',
    'emojiCategory.other': 'Other',
    
    // Settings - Theme
    'settings.theme': 'Theme',
    'settings.themeDescription': 'Choose your preferred theme',
    'settings.themeOriginal': 'Original (White & Green)',
    'settings.themeOriginalDesc': 'Improved contrast white theme with better visibility',
    'settings.themeRecycled': 'Recycled (Warm & Eco)',
    'settings.themeRecycledDesc': 'Warm eco-friendly peach and cream tones',
    'settings.themeDarkBrown': 'Dark Brown Theme',
    'settings.themeDarkBrownDesc': 'Dark warm brown with green accents',
    'settings.themeBlack': 'Black Theme',
    'settings.themeBlackDesc': 'Pure black background with high contrast',
    'settings.themeBlue': 'Blue Theme',
    'settings.themeBlueDesc': 'Cool blue tones with light backgrounds',
    'settings.themeGreen': 'Green Theme',
    'settings.themeGreenDesc': 'Natural earth tones with green accents',
    'settings.themeSoftPink': 'Soft Pink Theme',
    'settings.themeSoftPinkDesc': 'Warm and cozy pink tones',
    'settings.themeBrightPink': 'Bright Pink Theme',
    'settings.themeBrightPinkDesc': 'Vibrant and energetic pink theme',
    'settings.themeYellow': 'Yellow Theme',
    'settings.themeYellowDesc': 'Warm and bright yellow tones',
    'settings.themeMintRed': 'Mint-Red Theme',
    'settings.themeMintRedDesc': 'Fresh mint with vibrant red accents',
    'settings.themeDarkGold': 'Dark Gold Theme',
    'settings.themeDarkGoldDesc': 'Elegant dark theme with gold accents',
    
    // Analytics
    'analytics.description': 'Track your food waste and savings',
    'analytics.loadFailed': 'Failed to load analytics',
    'analytics.loadGroupFailed': 'Failed to load group',
    'analytics.noData': 'No Analytics Data',
    'analytics.noDataDescription': 'Start tracking food items to see analytics here.',
    'analytics.totalItems': 'Total Items',
    'analytics.itemsTracked': 'Items tracked in period',
    'analytics.itemsUsed': 'Items Used',
    'analytics.itemsUsedDescription': 'Successfully consumed',
    'analytics.itemsWasted': 'Items Wasted',
    'analytics.itemsWastedDescription': 'Thrown away or expired',
    'analytics.wastePercentage': 'Waste %',
    'analytics.wastePercentageDescription': 'Percentage of items wasted',
    'analytics.totalWasteValue': 'Waste Value',
    'analytics.totalWasteValueDescription': 'Estimated value of wasted items',
    'analytics.avgDaysBeforeExpiry': 'Avg Days',
    'analytics.avgDaysDescription': 'Average days before expiry when discarded',
    'analytics.categoryBreakdown': 'Category Breakdown',
    'analytics.locationBreakdown': 'Location Breakdown',
    'analytics.monthlyTrends': 'Monthly Trends',
    'analytics.mostWastedItems': 'Most Wasted Items',
    'analytics.disposalReasons': 'Disposal Reasons',
    'analytics.expiryPatterns': 'Expiry Patterns',
    'analytics.used': 'used',
    'analytics.wasted': 'wasted',
    'analytics.month': 'Month',
    'analytics.added': 'Added',
    'analytics.wastePercent': 'Waste %',
    'analytics.value': 'Value',
    'analytics.days': 'days',
    'analytics.discardedVeryLate': 'Discarded Very Late (>7 days after)',
    'analytics.discardedAfterExpiry': 'Discarded After Expiry',
    'analytics.discardedOnExpiry': 'Discarded On Expiry Day',
    'analytics.discardedNearExpiry': 'Discarded Near Expiry (1-3 days)',
    'analytics.discardedWellBefore': 'Discarded Well Before (>3 days)',
    'analytics.avgDaysSincePurchase': 'Avg Days Since Purchase',
    'analytics.period': 'Period',
    'analytics.lastMonth': 'Last Month',
    'analytics.last3Months': 'Last 3 Months',
    'analytics.last6Months': 'Last 6 Months',
    'analytics.lastYear': 'Last Year',
    
    // Lists (Shopping & Wish)
    'lists.title': 'Lists',
    'lists.description': 'Manage your shopping list and wish list',
    'lists.shoppingList': 'Shopping List',
    'lists.wishList': 'Wish List',
    'lists.addItem': 'Add item...',
    'lists.quantity': 'Quantity',
    'lists.notes': 'Notes (optional)',
    'lists.nameRequired': 'Item name is required',
    'lists.itemAdded': 'Item added successfully',
    'lists.itemUpdated': 'Item updated',
    'lists.itemDeleted': 'Item deleted',
    'lists.addFailed': 'Failed to add item',
    'lists.updateFailed': 'Failed to update item',
    'lists.deleteFailed': 'Failed to delete item',
    'lists.confirmDelete': 'Are you sure you want to delete this item?',
    'lists.editItem': 'Edit Item',
    'lists.itemName': 'Item name',
    'lists.unpurchased': 'To Buy',
    'lists.purchased': 'Purchased',
    'lists.clearCompleted': 'Clear Completed',
    'lists.confirmClearCompleted': 'Are you sure you want to clear all purchased items?',
    'lists.itemsCleared': '{count} items cleared',
    'lists.clearFailed': 'Failed to clear items',
    'lists.addToFoodItems': 'Add to Food Items',
    'lists.noItems': 'No shopping items yet',
    'lists.addFirstItem': 'Add your first item to get started!',
    'lists.noWishItems': 'No wish items yet',
    'lists.addFirstWishItem': 'Add your first wish item to get started!',
    'lists.noGroup': 'No group found',
    'lists.loadGroupFailed': 'Failed to load group',
    'lists.loadFailed': 'Failed to load items',
    
    // Groups
    'groups.title': 'Groups',
    'groups.description': 'Manage your groups and members',
    'groups.createGroup': 'Create Group',
    'groups.joinGroup': 'Join Group',
    'groups.inviteMember': 'Invite Member',
    'groups.groupName': 'Group Name',
    'groups.groupDescription': 'Description (optional)',
    'groups.inviteCode': 'Invite Code',
    'groups.members': 'Members',
    'groups.role': 'Role',
    'groups.owner': 'Owner',
    'groups.admin': 'Admin',
    'groups.member': 'Member',
    'groups.removeMember': 'Remove Member',
    'groups.updateRole': 'Update Role',
    'groups.deleteGroup': 'Delete Group',
    'groups.noGroups': 'No groups found',
    'groups.noInvitations': 'No pending invitations',
    'groups.pendingInvitations': 'Pending Invitations',
    'groups.accept': 'Accept',
    'groups.decline': 'Decline',
    'groups.copyCode': 'Copy Code',
    'groups.codeCopied': 'Invite code copied to clipboard',
    'groups.groupCreated': 'Group created successfully',
    'groups.groupUpdated': 'Group updated successfully',
    'groups.groupDeleted': 'Group deleted successfully',
    'groups.memberRemoved': 'Member removed successfully',
    'groups.roleUpdated': 'Role updated successfully',
    'groups.invitationSent': 'Invitation sent successfully',
    'groups.groupJoined': 'Successfully joined group',
    'groups.joinFailed': 'Failed to join group',
    'groups.groupFull': 'Group is full',
    'groups.enterEmail': 'Enter email address',
    'groups.emailSent': 'Invitation email sent',
    'groups.emailRequired': 'Email is required',
    'groups.confirmDelete': 'Are you sure you want to delete this group?',
    'groups.confirmRemove': 'Are you sure you want to remove this member?',
    'groups.confirmLeave': 'Are you sure you want to leave this group?',
    'groups.leaveGroup': 'Leave Group',
    'groups.leaveGroupSuccess': 'Successfully left group',
    'groups.leaveGroupFailed': 'Failed to leave group',
    'groups.groupChanged': 'Group changed',
    'groups.noGroup': 'No group selected',
    'groups.manageGroups': 'Manage Groups',
  },
  zh: {
    // Navigation  
    'nav.dashboard': '仪表板',
    'nav.addItem': '添加项目',
    'nav.locations': '位置',
    'nav.categories': '分类',
    'nav.lists': '列表',
    'nav.analytics': '分析',
    'nav.logout': '登出',
    
    // Landing Page
    'landing.title': '再也不让食物浪费',
    'landing.heroTitle': '不再让食物浪费',
    'landing.heroSubline': '追踪保质期、智能提醒、省钱省心。',
    'landing.subtitle': '智能厨房保质期跟踪。在食品过期前获得通知，减少食物浪费并节省金钱。',
    'landing.getStarted': '开始使用',
    'landing.learnMore': '了解更多',
    'landing.downloadApp': '下载应用',
    'landing.download': '下载',
    'landing.trustOffline': '离线模式',
    'landing.trustSync': '云端同步',
    'landing.trustPrivacy': '隐私优先',
    'landing.smartAlerts': '智能提醒',
    'landing.badgeTrack': '追踪物品',
    'landing.badgeReminders': '提醒',
    'landing.badgeSaveMoney': '省钱',
    'landing.howItWorks': '使用方式',
    'landing.step1Title': '添加物品',
    'landing.step1Desc': '为每个物品选择分类和存放位置。',
    'landing.step2Title': '设置保质期',
    'landing.step2Desc': '输入或扫描保质期，我们帮您追踪。',
    'landing.step3Title': '收到提醒',
    'landing.step3Desc': '在过期前通知您，及时使用。',
    'landing.screenshotsTitle': '看看应用效果',
    'landing.screenshotList': '物品列表',
    'landing.screenshotCategories': '设置分类',
    'landing.screenshotCalendar': '日历视图',
    'landing.screenshotAddPhoto': '添加照片',
    'landing.screenshotSettingsTheme': '主题与设置',
    'landing.screenshotListDesc': '浏览和筛选物品、按名称搜索，一眼查看过期状态。',
    'landing.screenshotCategoriesDesc': '选择分类主题，快速添加推荐分类到列表。',
    'landing.screenshotCalendarDesc': '按日期查看物品，了解每天即将过期的项目。',
    'landing.screenshotAddPhotoDesc': '拍照、从相册选择或使用食物表情添加照片。',
    'landing.screenshotSettingsThemeDesc': '更改语言、选择主题并管理应用偏好。',
    'landing.worksOfflineSync': '支持离线 • 多设备同步',
    'landing.privacyFirstTitle': '隐私优先设计',
    'landing.privacyNoSell': '不出售您的数据',
    'landing.privacyEncrypted': '传输加密',
    'landing.privacyControl': '您可随时删除数据',
    'landing.privacyPolicyLink': '隐私政策',
    'landing.termsLink': '条款与条件',
    'landing.whyChoose': '为什么选择过期提醒？',
    'landing.smartTracking': '智能跟踪',
    'landing.smartTrackingDesc': '通过我们直观的界面轻松跟踪所有食品的保质期。',
    'landing.timelyAlerts': '及时提醒',
    'landing.timelyAlertsDesc': '在食品过期前获得通知，以便及时使用。',
    'landing.visualDashboard': '可视化仪表板',
    'landing.visualDashboardDesc': '通过彩色状态指示器一目了然地查看您的库存。',
    'landing.reduceWaste': '减少浪费',
    'landing.reduceWasteDesc': '通过减少食物浪费来帮助环境并节省金钱。',
    'landing.crossPlatform': '跨平台',
    'landing.crossPlatformDesc': '在网页、iOS和Android上可用，实现无缝同步。',
    'landing.securePrivate': '安全私密',
    'landing.securePrivateDesc': '您的数据安全存储并在所有设备间同步。',
    'landing.downloadTitle': '下载过期提醒',
    'landing.downloadDesc': '获取移动应用程序以获得最佳的通知和离线访问体验。',
    'landing.preferBrowser': '更喜欢在浏览器中使用？',
    'landing.launchWebApp': '启动网页应用',
    'landing.activeUsers': '活跃用户',
    'landing.itemsTracked': '跟踪项目',
    'landing.wasteReduced': '减少食物浪费',
    'landing.appStoreRating': '应用商店评分',
    
    // Dashboard
    'dashboard.recentItems': '最近项目',
    'dashboard.getStarted': '添加您的第一个食品项目以开始跟踪过期日期！',
    'dashboard.welcome': '欢迎！管理您的食品项目并跟踪过期日期。',
    'dashboard.fresh': '新鲜',
    'dashboard.expiringSoon': '即将过期',
    'dashboard.expired': '已过期',
    'dashboard.total': '总计',
    'dashboard.items': '项目',
    'dashboard.search': '搜索项目...',
    'dashboard.noItems': '未找到项目',
    'dashboard.addFirstItem': '添加您的第一个食品项目以开始跟踪！',
    'dashboard.confirmDelete': '您确定要删除此项目吗？',
    'dashboard.itemDeleted': '项目删除成功',
    'dashboard.deleteFailed': '删除项目失败',
    'dashboard.deleteMultiple': '删除 {count} 个项目？',
    'dashboard.itemsDeleted': '{count} 个项目已删除',
    'dashboard.deleteFailedMultiple': '删除项目失败',
    'dashboard.uncategorized': '未分类',
    'dashboard.unknown': '未知',
    'dashboard.noLocation': '无位置',
    'dashboard.allCategories': '所有分类',
    'dashboard.allLocations': '所有位置',
    'dashboard.sortByExpiry': '按过期日期排序',
    'dashboard.sortByName': '按名称排序',
    'dashboard.sortByCategory': '按分类排序',
    'dashboard.sortByLocation': '按位置排序',
    'dashboard.sortByDateAdded': '按添加日期排序',
    'dashboard.ascending': '升序',
    'dashboard.descending': '降序',
    'dashboard.gridView': '网格视图',
    'dashboard.listView': '列表视图',
    'dashboard.itemsSelected': '已选择 {count} 个项目',
    'dashboard.deleteSelected': '删除所选',
    'dashboard.clearSelection': '清除选择',
    'dashboard.statusFresh': '新鲜',
    'dashboard.statusExpiringSoon': '即将过期',
    'dashboard.statusExpired': '已过期',
    'dashboard.daysAgo': '{count} 天前',
    'dashboard.daysLeft': '还剩 {count} 天',
    'dashboard.freshItems': '新鲜项目',
    'dashboard.expiringItems': '即将过期项目',
    'dashboard.expiredItems': '已过期项目',
    'dashboard.loadDataFailed': '加载数据失败',
    'dashboard.loadCategoriesFailed': '加载分类失败',
    'dashboard.loadLocationsFailed': '加载位置失败',
    'dashboard.unknownError': '未知错误',
    'dashboard.checkConnection': '请检查您的互联网连接后重试。',
    
    // Home/Welcome
    'home.welcome': '欢迎回来！',
    'home.categories': '分类',
    
    // Status
    'status.indate': '未过期',
    'status.expiring': '即将过期',
    'status.expired': '已过期',
    'status.items': '项目',
    'status.loading': '加载中...',
    'status.error': '错误',
    'status.retry': '重试',
    'status.refresh': '刷新',
    'status.viewAll': '查看全部',
    'status.noItems': '未找到{status}项目',
    'status.itemsStored': '项目已存储',
    'status.total': '总计',
    
    // Items
    'item.quantity': '数量',
    'item.expirestoday': '今天过期',
    'item.dayLeft': '天剩余',
    'item.daysLeft': '天剩余',
    'item.dayAgo': '天前',
    'item.daysAgo': '天前',
    
    // Actions
    'action.add': '添加',
    'action.edit': '编辑',
    'action.delete': '删除',
    'actions.refresh': '刷新',
    'actions.retry': '重试',
    
    // Alerts
    'alert.deleteMessage': '您确定要删除吗',
    'alert.success': '成功',
    'alert.deleteFailed': '删除项目失败',
    
    // Form
    'form.itemName': '项目',
    
    // Lists
    'list.noItems': '未找到项目。添加一些项目以开始！',
    
    // Cleanup
    'cleanup.confirmMessage': '您确定要清理过期项目吗？',
    'cleanup.success': '清理成功完成',
    'cleanup.failed': '清理过期项目失败',
    'cleanup.itemsDeleted': '项目已删除',
    'cleanup.cleanupExpired': '清理过期',
    'cleanup.inProgress': '清理中...',
    
    // Categories
    'categories.title': '分类',
    'categories.addNew': '添加新分类',
    'categories.name': '分类名称',
    'categories.description': '描述',
    'categories.icon': '图标',
    'categories.color': '颜色',
    'categories.delete': '删除分类',
    'categories.deleteConfirm': '您确定要删除此分类吗？',
    'categories.edit': '编辑分类',
    'categories.save': '保存分类',
    'categories.cancel': '取消',
    'categories.noCategories': '未找到分类。添加您的第一个分类以开始！',
    'categories.preview': '预览',
    
    // Locations
    'locations.title': '存储位置',
    'locations.addNew': '添加新位置',
    'locations.name': '位置名称',
    'locations.description': '描述',
    'locations.temperature': '温度',
    'locations.room': '室温',
    'locations.refrigerated': '冷藏',
    'locations.frozen': '冷冻',
    'locations.delete': '删除位置',
    'locations.deleteConfirm': '您确定要删除此位置吗？',
    'locations.edit': '编辑位置',
    'locations.save': '保存位置',
    'locations.cancel': '取消',
    'locations.noLocations': '未找到位置。添加您的第一个存储位置以开始！',
    
    // Food Items
    'foodItems.title': '食品项目',
    'foodItems.addNew': '添加新项目',
    'foodItems.name': '项目名称',
    'foodItems.category': '分类',
    'foodItems.location': '存储位置',
    'foodItems.expiryDate': '过期日期',
    'foodItems.quantity': '数量',
    'foodItems.notes': '备注',
    'foodItems.reminderDays': '提醒天数',
    'foodItems.save': '保存项目',
    'foodItems.cancel': '取消',
    'foodItems.edit': '编辑项目',
    'foodItems.delete': '删除项目',
    'foodItems.deleteConfirm': '您确定要删除此项目吗？',
    'foodItems.noItems': '未找到食品项目。添加您的第一个项目以开始跟踪！',
    'foodItems.selectCategory': '选择分类',
    'foodItems.selectLocation': '选择位置',
    'foodItems.notFound': '未找到项目',
    'foodItems.loadFailed': '加载项目失败',
    'foodItems.createFailed': '创建项目失败',
    'foodItems.updateFailed': '更新项目失败',
    'foodItems.loadCategoriesFailed': '加载分类和位置失败',
    'foodItems.groupLoadFailed': '无法加载您的组。请刷新页面重试。',
    'foodItems.categoryNotFound': '找不到您的分类？',
    'foodItems.locationNotFound': '需要新位置？',
    'foodItems.reminderDaysDesc': '过期前几天提醒您（默认：3天）',
    'foodItems.tips': '提示：',
    'foodItems.tip1': '项目名称要具体，便于识别',
    'foodItems.tip2': '仔细检查过期日期，避免错误',
    'foodItems.tip3': '在备注字段中记录特殊存储说明',
    'foodItems.tip4': '根据您使用物品的速度设置提醒天数',
    
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.add': '添加',
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.confirm': '确认',
    'common.close': '关闭',
    'common.created': '已创建',
    
    // Validation
    'validation.required': '此字段为必填项',
    'validation.nameRequired': '名称为必填项',
    'validation.categoryRequired': '分类为必填项',
    'validation.locationRequired': '位置为必填项',
    'validation.dateRequired': '日期为必填项',
    'validation.quantityRequired': '数量为必填项',
    
    // Auth
    'auth.login': '登录',
    'auth.logout': '登出',
    'auth.demo': '演示模式',
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.displayName': '显示名称',
    'auth.forgotPassword': '忘记密码？',
    'auth.createAccount': '创建账户',
    'auth.alreadyHaveAccount': '已有账户？',
    'auth.dontHaveAccount': '没有账户？',
    
    // Emoji Categories
    'emojiCategory.food': '食品饮料',
    'emojiCategory.personalCare': '美容个护',
    'emojiCategory.medical': '健康医疗',
    'emojiCategory.household': '家居用品',
    'emojiCategory.chemical': '汽车化工',
    'emojiCategory.other': '其他',
    
    // Settings - Theme
    'settings.theme': '主题',
    'settings.themeDescription': '选择您喜欢的主题',
    'settings.themeOriginal': '原始（白色和绿色）',
    'settings.themeOriginalDesc': '对比度更好的白色主题，提高可见性',
    'settings.themeRecycled': '回收（温暖和环保）',
    'settings.themeRecycledDesc': '温暖的环保桃色和奶油色调',
    'settings.themeDarkBrown': '深棕色主题',
    'settings.themeDarkBrownDesc': '深色温暖的棕色配绿色点缀',
    'settings.themeBlack': '黑色主题',
    'settings.themeBlackDesc': '纯黑色背景，高对比度',
    'settings.themeBlue': '蓝色主题',
    'settings.themeBlueDesc': '冷色调蓝色配浅色背景',
    'settings.themeGreen': '绿色主题',
    'settings.themeGreenDesc': '自然大地色调配绿色点缀',
    'settings.themeSoftPink': '柔粉色主题',
    'settings.themeSoftPinkDesc': '温暖舒适的粉色色调',
    'settings.themeBrightPink': '亮粉色主题',
    'settings.themeBrightPinkDesc': '充满活力的粉色主题',
    'settings.themeYellow': '黄色主题',
    'settings.themeYellowDesc': '温暖明亮的黄色色调',
    'settings.themeMintRed': '薄荷红主题',
    'settings.themeMintRedDesc': '清新的薄荷配鲜艳的红色点缀',
    'settings.themeDarkGold': '深金色主题',
    'settings.themeDarkGoldDesc': '优雅的深色主题配金色点缀',
    
    // Lists (Shopping & Wish)
    'lists.title': '列表',
    'lists.description': '管理您的购物清单和愿望清单',
    'lists.shoppingList': '购物清单',
    'lists.wishList': '愿望清单',
    'lists.addItem': '添加项目...',
    'lists.quantity': '数量',
    'lists.notes': '备注（可选）',
    'lists.nameRequired': '项目名称为必填项',
    'lists.itemAdded': '项目添加成功',
    'lists.itemUpdated': '项目已更新',
    'lists.itemDeleted': '项目已删除',
    'lists.addFailed': '添加项目失败',
    'lists.updateFailed': '更新项目失败',
    'lists.deleteFailed': '删除项目失败',
    'lists.confirmDelete': '您确定要删除此项目吗？',
    'lists.editItem': '编辑项目',
    'lists.itemName': '项目名称',
    'lists.unpurchased': '待购买',
    'lists.purchased': '已购买',
    'lists.clearCompleted': '清除已完成',
    'lists.confirmClearCompleted': '您确定要清除所有已购买的项目吗？',
    'lists.itemsCleared': '已清除 {count} 个项目',
    'lists.clearFailed': '清除项目失败',
    'lists.addToFoodItems': '添加到食品项目',
    'lists.noItems': '还没有购物项目',
    'lists.addFirstItem': '添加您的第一个项目以开始！',
    'lists.noWishItems': '还没有愿望项目',
    'lists.addFirstWishItem': '添加您的第一个愿望项目以开始！',
    'lists.noGroup': '未找到组',
    'lists.loadGroupFailed': '加载组失败',
    'lists.loadFailed': '加载项目失败',
    
    // Groups
    'groups.title': '组',
    'groups.description': '管理您的组和成员',
    'groups.createGroup': '创建组',
    'groups.joinGroup': '加入组',
    'groups.inviteMember': '邀请成员',
    'groups.groupName': '组名称',
    'groups.groupDescription': '描述（可选）',
    'groups.inviteCode': '邀请码',
    'groups.members': '成员',
    'groups.role': '角色',
    'groups.owner': '所有者',
    'groups.admin': '管理员',
    'groups.member': '成员',
    'groups.removeMember': '移除成员',
    'groups.updateRole': '更新角色',
    'groups.deleteGroup': '删除组',
    'groups.noGroups': '未找到组',
    'groups.noInvitations': '没有待处理的邀请',
    'groups.pendingInvitations': '待处理的邀请',
    'groups.accept': '接受',
    'groups.decline': '拒绝',
    'groups.copyCode': '复制代码',
    'groups.codeCopied': '邀请码已复制到剪贴板',
    'groups.groupCreated': '组创建成功',
    'groups.groupUpdated': '组更新成功',
    'groups.groupDeleted': '组删除成功',
    'groups.memberRemoved': '成员移除成功',
    'groups.roleUpdated': '角色更新成功',
    'groups.invitationSent': '邀请发送成功',
    'groups.groupJoined': '成功加入组',
    'groups.joinFailed': '加入组失败',
    'groups.groupFull': '组已满',
    'groups.enterEmail': '输入电子邮件地址',
    'groups.emailSent': '邀请邮件已发送',
    'groups.emailRequired': '电子邮件是必需的',
    'groups.confirmDelete': '您确定要删除此组吗？',
    'groups.confirmRemove': '您确定要移除此成员吗？',
    'groups.confirmLeave': '您确定要离开此组吗？',
    'groups.leaveGroup': '离开组',
    'groups.leaveGroupSuccess': '成功离开组',
    'groups.leaveGroupFailed': '离开组失败',
    'groups.groupChanged': '组已更改',
    'groups.noGroup': '未选择组',
    'groups.manageGroups': '管理组',
  },
  ja: {
    // Navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.addItem': 'アイテム追加',
    'nav.locations': '場所',
    'nav.categories': 'カテゴリ',
    'nav.lists': 'リスト',
    'nav.analytics': '分析',
    'nav.logout': 'ログアウト',
    
    // Landing Page
    'landing.title': '食品を無駄にしないスマートアプリ',
    'landing.heroTitle': 'もう食品を無駄にしない',
    'landing.heroSubline': '賞味期限を記録し、スマートリマインダーでお金を節約。',
    'landing.subtitle': 'キッチンのためのスマート賞味期限追跡。食品が期限切れになる前に通知を受け取り、食品廃棄を減らしてお金を節約しましょう。',
    'landing.getStarted': '始める',
    'landing.learnMore': '詳細を見る',
    'landing.downloadApp': 'アプリをダウンロード',
    'landing.download': 'ダウンロード',
    'landing.trustOffline': 'オフライン対応',
    'landing.trustSync': 'クラウド同期',
    'landing.trustPrivacy': 'プライバシー優先',
    'landing.smartAlerts': 'スマートアラート',
    'landing.badgeTrack': 'アイテムを追跡',
    'landing.badgeReminders': 'リマインダー',
    'landing.badgeSaveMoney': '節約',
    'landing.howItWorks': '使い方',
    'landing.step1Title': 'アイテムを追加',
    'landing.step1Desc': 'カテゴリと保管場所を選びます。',
    'landing.step2Title': '賞味期限を設定',
    'landing.step2Desc': '賞味期限を入力またはスキャンして追跡。',
    'landing.step3Title': 'リマインダーを受け取る',
    'landing.step3Desc': '期限前に通知し、期限内に使えるようにします。',
    'landing.screenshotsTitle': 'アプリの様子',
    'landing.screenshotList': 'アイテム一覧',
    'landing.screenshotCategories': 'カテゴリ設定',
    'landing.screenshotCalendar': 'カレンダー表示',
    'landing.screenshotAddPhoto': '写真を追加',
    'landing.screenshotSettingsTheme': 'テーマと設定',
    'landing.screenshotListDesc': 'アイテムを一覧・フィルターし、名前で検索して期限をひと目で確認。',
    'landing.screenshotCategoriesDesc': 'カテゴリテーマを選んで、おすすめカテゴリをすばやく追加。',
    'landing.screenshotCalendarDesc': '日付ごとにアイテムを表示し、その日に期限のものを確認。',
    'landing.screenshotAddPhotoDesc': '撮影、ギャラリーから選択、またはフード絵文字で写真を追加。',
    'landing.screenshotSettingsThemeDesc': '言語の変更、テーマの選択、アプリ設定の管理。',
    'landing.worksOfflineSync': 'オフライン対応 • デバイス間同期',
    'landing.privacyFirstTitle': 'プライバシーを最優先に設計',
    'landing.privacyNoSell': 'データを販売しません',
    'landing.privacyEncrypted': '通信は暗号化',
    'landing.privacyControl': '削除はお客様の管理下',
    'landing.privacyPolicyLink': 'プライバシーポリシー',
    'landing.termsLink': '利用規約',
    'landing.whyChoose': 'なぜExpiry Alertを選ぶのか？',
    'landing.smartTracking': 'スマート追跡',
    'landing.smartTrackingDesc': '直感的なインターフェースですべての食品の賞味期限を簡単に追跡できます。',
    'landing.timelyAlerts': 'タイムリーアラート',
    'landing.timelyAlertsDesc': '食品が期限切れになる前に通知を受け取り、時間内に使用できます。',
    'landing.visualDashboard': 'ビジュアルダッシュボード',
    'landing.visualDashboardDesc': 'カラーコード化されたステータスインジケーターで在庫を一目で確認できます。',
    'landing.reduceWaste': '廃棄削減',
    'landing.reduceWasteDesc': '食品廃棄を減らして環境を守り、お金を節約しましょう。',
    'landing.crossPlatform': 'クロスプラットフォーム',
    'landing.crossPlatformDesc': 'ウェブ、iOS、Androidで利用可能でシームレスな同期を実現。',
    'landing.securePrivate': 'セキュアでプライベート',
    'landing.securePrivateDesc': 'あなたのデータは安全に保存され、すべてのデバイス間で同期されます。',
    'landing.downloadTitle': 'Expiry Alertをダウンロード',
    'landing.downloadDesc': '通知とオフラインアクセスの最高の体験のためにモバイルアプリを入手してください。',
    'landing.preferBrowser': 'ブラウザでの使用を希望しますか？',
    'landing.launchWebApp': 'ウェブアプリを起動',
    'landing.activeUsers': 'アクティブユーザー',
    'landing.itemsTracked': '追跡アイテム',
    'landing.wasteReduced': '食品廃棄削減',
    'landing.appStoreRating': 'App Store評価',
    
    // Dashboard
    'dashboard.recentItems': '最近のアイテム',
    'dashboard.getStarted': '最初の食品アイテムを追加して賞味期限の追跡を始めましょう！',
    'dashboard.welcome': 'ようこそ！食品アイテムを管理し、賞味期限を追跡します。',
    'dashboard.fresh': '新鮮',
    'dashboard.expiringSoon': '期限間近',
    'dashboard.expired': '期限切れ',
    'dashboard.total': '合計',
    'dashboard.items': 'アイテム',
    'dashboard.search': 'アイテムを検索...',
    'dashboard.noItems': 'アイテムが見つかりません',
    'dashboard.addFirstItem': '最初の食品アイテムを追加して追跡を始めましょう！',
    'dashboard.confirmDelete': 'このアイテムを削除してもよろしいですか？',
    'dashboard.itemDeleted': 'アイテムが正常に削除されました',
    'dashboard.deleteFailed': 'アイテムの削除に失敗しました',
    'dashboard.deleteMultiple': '{count} 個のアイテムを削除しますか？',
    'dashboard.itemsDeleted': '{count} 個のアイテムが削除されました',
    'dashboard.deleteFailedMultiple': 'アイテムの削除に失敗しました',
    'dashboard.uncategorized': '未分類',
    'dashboard.unknown': '不明',
    'dashboard.noLocation': '場所なし',
    'dashboard.allCategories': 'すべてのカテゴリ',
    'dashboard.allLocations': 'すべての場所',
    'dashboard.sortByExpiry': '賞味期限で並び替え',
    'dashboard.sortByName': '名前で並び替え',
    'dashboard.sortByCategory': 'カテゴリで並び替え',
    'dashboard.sortByLocation': '場所で並び替え',
    'dashboard.sortByDateAdded': '追加日で並び替え',
    'dashboard.ascending': '昇順',
    'dashboard.descending': '降順',
    'dashboard.gridView': 'グリッド表示',
    'dashboard.listView': 'リスト表示',
    'dashboard.itemsSelected': '{count} 個のアイテムが選択されました',
    'dashboard.deleteSelected': '選択を削除',
    'dashboard.clearSelection': '選択をクリア',
    'dashboard.statusFresh': '新鮮',
    'dashboard.statusExpiringSoon': '期限間近',
    'dashboard.statusExpired': '期限切れ',
    'dashboard.daysAgo': '{count} 日前',
    'dashboard.daysLeft': '残り {count} 日',
    'dashboard.freshItems': '新鮮なアイテム',
    'dashboard.expiringItems': '期限間近のアイテム',
    'dashboard.expiredItems': '期限切れアイテム',
    'dashboard.loadDataFailed': 'データの読み込みに失敗しました',
    'dashboard.loadCategoriesFailed': 'カテゴリの読み込みに失敗しました',
    'dashboard.loadLocationsFailed': '場所の読み込みに失敗しました',
    'dashboard.unknownError': '不明なエラー',
    'dashboard.checkConnection': 'インターネット接続を確認して再試行してください。',
    
    // Home/Welcome
    'home.welcome': 'おかえりなさい！',
    'home.categories': 'カテゴリ',
    
    // Status
    'status.indate': '期限内',
    'status.expiring': '期限間近',
    'status.expired': '期限切れ',
    'status.items': 'アイテム',
    'status.loading': '読み込み中...',
    'status.error': 'エラー',
    'status.retry': '再試行',
    'status.refresh': '更新',
    'status.viewAll': 'すべて表示',
    'status.noItems': '{status}アイテムが見つかりません',
    'status.itemsStored': 'アイテムが保存されました',
    'status.total': '合計',
    
    // Items
    'item.quantity': '数量',
    'item.expirestoday': '今日期限',
    'item.dayLeft': '日残り',
    'item.daysLeft': '日残り',
    'item.dayAgo': '日前',
    'item.daysAgo': '日前',
    
    // Actions
    'action.add': '追加',
    'action.edit': '編集',
    'action.delete': '削除',
    'actions.refresh': '更新',
    'actions.retry': '再試行',
    
    // Alerts
    'alert.deleteMessage': '削除してもよろしいですか',
    'alert.success': '成功',
    'alert.deleteFailed': 'アイテムの削除に失敗しました',
    
    // Form
    'form.itemName': 'アイテム',
    
    // Lists
    'list.noItems': 'アイテムが見つかりません。始めるためにアイテムを追加してください！',
    
    // Cleanup
    'cleanup.confirmMessage': '期限切れアイテムをクリーンアップしてもよろしいですか？',
    'cleanup.success': 'クリーンアップが正常に完了しました',
    'cleanup.failed': '期限切れアイテムのクリーンアップに失敗しました',
    'cleanup.itemsDeleted': 'アイテムが削除されました',
    'cleanup.cleanupExpired': '期限切れをクリーンアップ',
    'cleanup.inProgress': 'クリーンアップ中...',
    
    // Categories
    'categories.title': 'カテゴリ',
    'categories.addNew': '新しいカテゴリを追加',
    'categories.name': 'カテゴリ名',
    'categories.description': '説明',
    'categories.icon': 'アイコン',
    'categories.color': '色',
    'categories.delete': 'カテゴリを削除',
    'categories.deleteConfirm': 'このカテゴリを削除してもよろしいですか？',
    'categories.edit': 'カテゴリを編集',
    'categories.save': 'カテゴリを保存',
    'categories.cancel': 'キャンセル',
    'categories.noCategories': 'カテゴリが見つかりません。最初のカテゴリを追加して始めましょう！',
    'categories.preview': 'プレビュー',
    
    // Locations
    'locations.title': '保存場所',
    'locations.addNew': '新しい場所を追加',
    'locations.name': '場所名',
    'locations.description': '説明',
    'locations.temperature': '温度',
    'locations.room': '室温',
    'locations.refrigerated': '冷蔵',
    'locations.frozen': '冷凍',
    'locations.delete': '場所を削除',
    'locations.deleteConfirm': 'この場所を削除してもよろしいですか？',
    'locations.edit': '場所を編集',
    'locations.save': '場所を保存',
    'locations.cancel': 'キャンセル',
    'locations.noLocations': '場所が見つかりません。最初の保存場所を追加して始めましょう！',
    
    // Food Items
    'foodItems.title': '食品アイテム',
    'foodItems.addNew': '新しいアイテムを追加',
    'foodItems.name': 'アイテム名',
    'foodItems.category': 'カテゴリ',
    'foodItems.location': '保存場所',
    'foodItems.expiryDate': '賞味期限',
    'foodItems.quantity': '数量',
    'foodItems.notes': 'メモ',
    'foodItems.reminderDays': 'リマインダー日数',
    'foodItems.save': 'アイテムを保存',
    'foodItems.cancel': 'キャンセル',
    'foodItems.edit': 'アイテムを編集',
    'foodItems.delete': 'アイテムを削除',
    'foodItems.deleteConfirm': 'このアイテムを削除してもよろしいですか？',
    'foodItems.noItems': '食品アイテムが見つかりません。最初のアイテムを追加して追跡を始めましょう！',
    'foodItems.selectCategory': 'カテゴリを選択',
    'foodItems.selectLocation': '場所を選択',
    'foodItems.notFound': 'アイテムが見つかりません',
    'foodItems.loadFailed': 'アイテムの読み込みに失敗しました',
    'foodItems.createFailed': 'アイテムの作成に失敗しました',
    'foodItems.updateFailed': 'アイテムの更新に失敗しました',
    'foodItems.loadCategoriesFailed': 'カテゴリと場所の読み込みに失敗しました',
    'foodItems.groupLoadFailed': 'グループを読み込めませんでした。ページを更新して再試行してください。',
    'foodItems.categoryNotFound': 'カテゴリが見つかりませんか？',
    'foodItems.locationNotFound': '新しい場所が必要ですか？',
    'foodItems.reminderDaysDesc': '期限の何日前にリマインダーを送るか（デフォルト：3日）',
    'foodItems.tips': 'ヒント：',
    'foodItems.tip1': '識別しやすいようにアイテム名を具体的にしてください',
    'foodItems.tip2': '間違いを避けるため、賞味期限を再確認してください',
    'foodItems.tip3': '特別な保存方法はメモ欄に記録してください',
    'foodItems.tip4': 'アイテムの使用頻度に基づいてリマインダー日数を設定してください',
    
    // Common
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.edit': '編集',
    'common.delete': '削除',
    'common.add': '追加',
    'common.loading': '読み込み中...',
    'common.error': 'エラー',
    'common.success': '成功',
    'common.confirm': '確認',
    'common.close': '閉じる',
    'common.created': '作成済み',
    
    // Validation
    'validation.required': 'このフィールドは必須です',
    'validation.nameRequired': '名前は必須です',
    'validation.categoryRequired': 'カテゴリは必須です',
    'validation.locationRequired': '場所は必須です',
    'validation.dateRequired': '日付は必須です',
    'validation.quantityRequired': '数量は必須です',
    
    // Auth
    'auth.login': 'ログイン',
    'auth.logout': 'ログアウト',
    'auth.demo': 'デモモード',
    'auth.signIn': 'サインイン',
    'auth.signUp': 'サインアップ',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.confirmPassword': 'パスワード確認',
    'auth.displayName': '表示名',
    'auth.forgotPassword': 'パスワードを忘れましたか？',
    'auth.createAccount': 'アカウントを作成',
    'auth.alreadyHaveAccount': 'すでにアカウントをお持ちですか？',
    'auth.dontHaveAccount': 'アカウントをお持ちでないですか？',
    
    // Emoji Categories
    'emojiCategory.food': '食品・飲料',
    'emojiCategory.personalCare': '美容・パーソナルケア',
    'emojiCategory.medical': '健康・医療',
    'emojiCategory.household': '家庭用品',
    'emojiCategory.chemical': '自動車・化学',
    'emojiCategory.other': 'その他',
    
    // Settings - Theme
    'settings.theme': 'テーマ',
    'settings.themeDescription': 'お好みのテーマを選択',
    'settings.themeOriginal': 'オリジナル（白と緑）',
    'settings.themeOriginalDesc': '視認性を向上させた白テーマ',
    'settings.themeRecycled': 'リサイクル（温かみとエコ）',
    'settings.themeRecycledDesc': '温かみのあるエコフレンドリーな桃色とクリーム色',
    'settings.themeDarkBrown': 'ダークブラウンテーマ',
    'settings.themeDarkBrownDesc': '緑のアクセント付きダークウォームブラウン',
    'settings.themeBlack': 'ブラックテーマ',
    'settings.themeBlackDesc': '高コントラストの純黒背景',
    'settings.themeBlue': 'ブルーテーマ',
    'settings.themeBlueDesc': '明るい背景のクールなブルートーン',
    'settings.themeGreen': 'グリーテーマ',
    'settings.themeGreenDesc': '緑のアクセント付きナチュラルなアーストーン',
    'settings.themeSoftPink': 'ソフトピンクテーマ',
    'settings.themeSoftPinkDesc': '温かく心地よいピンクトーン',
    'settings.themeBrightPink': 'ブライトピンクテーマ',
    'settings.themeBrightPinkDesc': '鮮やかでエネルギッシュなピンクテーマ',
    'settings.themeYellow': 'イエローテーマ',
    'settings.themeYellowDesc': '温かく明るいイエロートーン',
    'settings.themeMintRed': 'ミントレッドテーマ',
    'settings.themeMintRedDesc': '鮮やかな赤のアクセント付きフレッシュミント',
    'settings.themeDarkGold': 'ダークゴールドテーマ',
    'settings.themeDarkGoldDesc': 'ゴールドのアクセント付きエレガントなダークテーマ',
    
    // Analytics
    'analytics.description': '食品廃棄と節約を追跡',
    'analytics.loadFailed': '分析データの読み込みに失敗しました',
    'analytics.loadGroupFailed': 'グループの読み込みに失敗しました',
    'analytics.noData': '分析データなし',
    'analytics.noDataDescription': '食品アイテムの追跡を開始して分析を表示します。',
    'analytics.totalItems': '総アイテム数',
    'analytics.itemsTracked': '期間中に追跡されたアイテム数',
    'analytics.itemsUsed': '使用済みアイテム',
    'analytics.itemsUsedDescription': '正常に消費されました',
    'analytics.itemsWasted': '廃棄アイテム',
    'analytics.itemsWastedDescription': '捨てられたまたは期限切れ',
    'analytics.wastePercentage': '廃棄率',
    'analytics.wastePercentageDescription': '廃棄されたアイテムの割合',
    'analytics.totalWasteValue': '廃棄価値',
    'analytics.totalWasteValueDescription': '廃棄されたアイテムの推定価値',
    'analytics.avgDaysBeforeExpiry': '平均日数',
    'analytics.avgDaysDescription': '廃棄時の期限までの平均日数',
    'analytics.categoryBreakdown': 'カテゴリ内訳',
    'analytics.locationBreakdown': '場所内訳',
    'analytics.monthlyTrends': '月次トレンド',
    'analytics.mostWastedItems': '最も廃棄されたアイテム',
    'analytics.disposalReasons': '廃棄理由',
    'analytics.expiryPatterns': '期限パターン',
    'analytics.used': '使用済み',
    'analytics.wasted': '廃棄済み',
    'analytics.month': '月',
    'analytics.added': '追加',
    'analytics.wastePercent': '廃棄率',
    'analytics.value': '価値',
    'analytics.days': '日',
    'analytics.discardedVeryLate': '非常に遅れて廃棄（期限後7日以上）',
    'analytics.discardedAfterExpiry': '期限後廃棄',
    'analytics.discardedOnExpiry': '期限日に廃棄',
    'analytics.discardedNearExpiry': '期限近くに廃棄（1-3日）',
    'analytics.discardedWellBefore': 'かなり前に廃棄（3日以上前）',
    'analytics.avgDaysSincePurchase': '購入からの平均日数',
    'analytics.period': '期間',
    'analytics.lastMonth': '先月',
    'analytics.last3Months': '過去3ヶ月',
    'analytics.last6Months': '過去6ヶ月',
    'analytics.lastYear': '去年',
    
    // Lists (Shopping & Wish)
    'lists.title': 'リスト',
    'lists.description': 'ショッピングリストとウィッシュリストを管理',
    'lists.shoppingList': 'ショッピングリスト',
    'lists.wishList': 'ウィッシュリスト',
    'lists.addItem': 'アイテムを追加...',
    'lists.quantity': '数量',
    'lists.notes': 'メモ（任意）',
    'lists.nameRequired': 'アイテム名は必須です',
    'lists.itemAdded': 'アイテムが正常に追加されました',
    'lists.itemUpdated': 'アイテムが更新されました',
    'lists.itemDeleted': 'アイテムが削除されました',
    'lists.addFailed': 'アイテムの追加に失敗しました',
    'lists.updateFailed': 'アイテムの更新に失敗しました',
    'lists.deleteFailed': 'アイテムの削除に失敗しました',
    'lists.confirmDelete': 'このアイテムを削除してもよろしいですか？',
    'lists.editItem': 'アイテムを編集',
    'lists.itemName': 'アイテム名',
    'lists.unpurchased': '購入予定',
    'lists.purchased': '購入済み',
    'lists.clearCompleted': '完了をクリア',
    'lists.confirmClearCompleted': 'すべての購入済みアイテムをクリアしてもよろしいですか？',
    'lists.itemsCleared': '{count} 個のアイテムがクリアされました',
    'lists.clearFailed': 'アイテムのクリアに失敗しました',
    'lists.addToFoodItems': '食品アイテムに追加',
    'lists.noItems': 'ショッピングアイテムはまだありません',
    'lists.addFirstItem': '最初のアイテムを追加して始めましょう！',
    'lists.noWishItems': 'ウィッシュアイテムはまだありません',
    'lists.addFirstWishItem': '最初のウィッシュアイテムを追加して始めましょう！',
    'lists.noGroup': 'グループが見つかりません',
    'lists.loadGroupFailed': 'グループの読み込みに失敗しました',
    'lists.loadFailed': 'アイテムの読み込みに失敗しました',
    
    // Groups
    'groups.title': 'グループ',
    'groups.description': 'グループとメンバーを管理',
    'groups.createGroup': 'グループを作成',
    'groups.joinGroup': 'グループに参加',
    'groups.inviteMember': 'メンバーを招待',
    'groups.groupName': 'グループ名',
    'groups.groupDescription': '説明（任意）',
    'groups.inviteCode': '招待コード',
    'groups.members': 'メンバー',
    'groups.role': '役割',
    'groups.owner': 'オーナー',
    'groups.admin': '管理者',
    'groups.member': 'メンバー',
    'groups.removeMember': 'メンバーを削除',
    'groups.updateRole': '役割を更新',
    'groups.deleteGroup': 'グループを削除',
    'groups.noGroups': 'グループが見つかりません',
    'groups.noInvitations': '保留中の招待はありません',
    'groups.pendingInvitations': '保留中の招待',
    'groups.accept': '承諾',
    'groups.decline': '拒否',
    'groups.copyCode': 'コードをコピー',
    'groups.codeCopied': '招待コードをクリップボードにコピーしました',
    'groups.groupCreated': 'グループが正常に作成されました',
    'groups.groupUpdated': 'グループが正常に更新されました',
    'groups.groupDeleted': 'グループが正常に削除されました',
    'groups.memberRemoved': 'メンバーが正常に削除されました',
    'groups.roleUpdated': '役割が正常に更新されました',
    'groups.invitationSent': '招待が正常に送信されました',
    'groups.groupJoined': 'グループに正常に参加しました',
    'groups.joinFailed': 'グループへの参加に失敗しました',
    'groups.groupFull': 'グループは満員です',
    'groups.enterEmail': 'メールアドレスを入力',
    'groups.emailSent': '招待メールが送信されました',
    'groups.emailRequired': 'メールアドレスは必須です',
    'groups.confirmDelete': 'このグループを削除してもよろしいですか？',
    'groups.confirmRemove': 'このメンバーを削除してもよろしいですか？',
    'groups.confirmLeave': 'このグループを離れてもよろしいですか？',
    'groups.leaveGroup': 'グループを離れる',
    'groups.leaveGroupSuccess': 'グループから正常に離れました',
    'groups.leaveGroupFailed': 'グループからの離脱に失敗しました',
    'groups.groupChanged': 'グループが変更されました',
    'groups.noGroup': 'グループが選択されていません',
    'groups.manageGroups': 'グループを管理',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    loadLanguage();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const loadLanguage = async () => {
    try {
      const savedLanguage = localStorage.getItem('app_language');
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'zh' || savedLanguage === 'ja')) {
        setLanguageState(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
      setLanguage('en'); // Fallback to English
    }
  };

  const setLanguage = async (lang: Language) => {
    try {
      localStorage.setItem('app_language', lang);
      setLanguageState(lang);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || translations['en'][key] || key;
    
    // Replace placeholders if params provided
    if (params) {
      Object.keys(params).forEach(param => {
        text = text.replace(new RegExp(`\\{${param}\\}`, 'g'), String(params[param]));
      });
    }
    
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 